[2024-04-15T00:09:12.616+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-15T00:09:12.652+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_and_load_equipment_sensors.load_to_mysql scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2024-04-15T00:09:12.677+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_and_load_equipment_sensors.load_to_mysql scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2024-04-15T00:09:12.680+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-15T00:09:12.739+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_to_mysql> on 2023-01-06 00:00:00+00:00
[2024-04-15T00:09:12.764+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3155) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-15T00:09:12.776+0000] {standard_task_runner.py:63} INFO - Started process 3209 to run task
[2024-04-15T00:09:12.777+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'extract_and_load_equipment_sensors', 'load_to_mysql', 'scheduled__2023-01-06T00:00:00+00:00', '--job-id', '977', '--raw', '--subdir', 'DAGS_FOLDER/dag_equipment_sensors.py', '--cfg-path', '/tmp/tmp8um4oecc']
[2024-04-15T00:09:12.788+0000] {standard_task_runner.py:91} INFO - Job 977: Subtask load_to_mysql
[2024-04-15T00:09:12.938+0000] {task_command.py:426} INFO - Running <TaskInstance: extract_and_load_equipment_sensors.load_to_mysql scheduled__2023-01-06T00:00:00+00:00 [running]> on host cb5b33b73a08
[2024-04-15T00:09:13.180+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_and_load_equipment_sensors' AIRFLOW_CTX_TASK_ID='load_to_mysql' AIRFLOW_CTX_EXECUTION_DATE='2023-01-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-06T00:00:00+00:00'
[2024-04-15T00:09:13.182+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-15T00:09:13.202+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-15T00:09:13.203+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_equipment_sensors.py", line 24, in load_to_mysql
    return load.df_to_mysql(table_name=EQUIPMENT_SENSORS, df=df)
           ^^^^
NameError: name 'load' is not defined. Did you mean: 'Load'?
[2024-04-15T00:09:13.230+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_sensors, task_id=load_to_mysql, execution_date=20230106T000000, start_date=20240415T000912, end_date=20240415T000913
[2024-04-15T00:09:13.253+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 977 for task load_to_mysql (name 'load' is not defined; 3209)
[2024-04-15T00:09:13.295+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-15T00:09:13.347+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-15T00:09:13.353+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
