[2024-04-14T20:38:21.989+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-14T20:38:22.006+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_and_load_equipment.extract_task manual__2024-04-14T20:38:20.145825+00:00 [queued]>
[2024-04-14T20:38:22.012+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_and_load_equipment.extract_task manual__2024-04-14T20:38:20.145825+00:00 [queued]>
[2024-04-14T20:38:22.012+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-14T20:38:22.025+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): extract_task> on 2024-04-14 20:38:20.145825+00:00
[2024-04-14T20:38:22.033+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=597) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-14T20:38:22.034+0000] {standard_task_runner.py:63} INFO - Started process 599 to run task
[2024-04-14T20:38:22.034+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'extract_and_load_equipment', 'extract_task', 'manual__2024-04-14T20:38:20.145825+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/dag_equipment.py', '--cfg-path', '/tmp/tmpunztrn39']
[2024-04-14T20:38:22.035+0000] {standard_task_runner.py:91} INFO - Job 20: Subtask extract_task
[2024-04-14T20:38:22.070+0000] {task_command.py:426} INFO - Running <TaskInstance: extract_and_load_equipment.extract_task manual__2024-04-14T20:38:20.145825+00:00 [running]> on host d0408c96e778
[2024-04-14T20:38:22.143+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_and_load_equipment' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2024-04-14T20:38:20.145825+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-14T20:38:20.145825+00:00'
[2024-04-14T20:38:22.144+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-14T20:38:22.145+0000] {logging_mixin.py:188} INFO - /opt/***/dados/equipment.json
[2024-04-14T20:38:22.159+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-14T20:38:22.160+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_equipment.py", line 15, in extract_to_dataframe
    df.to_sql(name='equipment_teste_airflow',df=df,con=conn, if_exists='append', index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
TypeError: NDFrame.to_sql() got an unexpected keyword argument 'df'
[2024-04-14T20:38:22.169+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment, task_id=extract_task, execution_date=20240414T203820, start_date=20240414T203822, end_date=20240414T203822
[2024-04-14T20:38:22.180+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 20 for task extract_task (NDFrame.to_sql() got an unexpected keyword argument 'df'; 599)
[2024-04-14T20:38:22.207+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-14T20:38:22.221+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-14T20:38:22.224+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
