[2024-04-15T00:13:54.781+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-15T00:13:54.812+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_and_load_equipment_sensors.load_to_mysql scheduled__2023-10-12T00:00:00+00:00 [queued]>
[2024-04-15T00:13:54.824+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_and_load_equipment_sensors.load_to_mysql scheduled__2023-10-12T00:00:00+00:00 [queued]>
[2024-04-15T00:13:54.826+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-15T00:13:54.853+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_to_mysql> on 2023-10-12 00:00:00+00:00
[2024-04-15T00:13:54.867+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=6109) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-15T00:13:54.869+0000] {standard_task_runner.py:63} INFO - Started process 6148 to run task
[2024-04-15T00:13:54.879+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'extract_and_load_equipment_sensors', 'load_to_mysql', 'scheduled__2023-10-12T00:00:00+00:00', '--job-id', '1785', '--raw', '--subdir', 'DAGS_FOLDER/dag_equipment_sensors.py', '--cfg-path', '/tmp/tmp3661b4aw']
[2024-04-15T00:13:54.880+0000] {standard_task_runner.py:91} INFO - Job 1785: Subtask load_to_mysql
[2024-04-15T00:13:54.976+0000] {task_command.py:426} INFO - Running <TaskInstance: extract_and_load_equipment_sensors.load_to_mysql scheduled__2023-10-12T00:00:00+00:00 [running]> on host cb5b33b73a08
[2024-04-15T00:13:55.168+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_and_load_equipment_sensors' AIRFLOW_CTX_TASK_ID='load_to_mysql' AIRFLOW_CTX_EXECUTION_DATE='2023-10-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-12T00:00:00+00:00'
[2024-04-15T00:13:55.171+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-15T00:13:55.202+0000] {warnings.py:110} WARNING - /opt/***/dags/dag_equipment_sensors.py:29: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return df.to_sql(EQUIPMENT_SENSORS, con=engine, if_exists='append', index=False)

[2024-04-15T00:13:55.205+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-15T00:13:55.206+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_equipment_sensors.py", line 29, in load_to_mysql
    return df.to_sql(EQUIPMENT_SENSORS, con=engine, if_exists='append', index=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'
[2024-04-15T00:13:55.227+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_sensors, task_id=load_to_mysql, execution_date=20231012T000000, start_date=20240415T001354, end_date=20240415T001355
[2024-04-15T00:13:55.250+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1785 for task load_to_mysql ('Engine' object has no attribute 'cursor'; 6148)
[2024-04-15T00:13:55.290+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-15T00:13:55.315+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-15T00:13:55.319+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
