[2024-04-15T00:11:58.309+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-15T00:11:58.344+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_and_load_equipment_sensors.load_to_mysql scheduled__2023-06-20T00:00:00+00:00 [queued]>
[2024-04-15T00:11:58.358+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_and_load_equipment_sensors.load_to_mysql scheduled__2023-06-20T00:00:00+00:00 [queued]>
[2024-04-15T00:11:58.359+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-15T00:11:58.378+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_to_mysql> on 2023-06-20 00:00:00+00:00
[2024-04-15T00:11:58.391+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4909) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-15T00:11:58.393+0000] {standard_task_runner.py:63} INFO - Started process 4942 to run task
[2024-04-15T00:11:58.394+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'extract_and_load_equipment_sensors', 'load_to_mysql', 'scheduled__2023-06-20T00:00:00+00:00', '--job-id', '1461', '--raw', '--subdir', 'DAGS_FOLDER/dag_equipment_sensors.py', '--cfg-path', '/tmp/tmp6c8glc3j']
[2024-04-15T00:11:58.395+0000] {standard_task_runner.py:91} INFO - Job 1461: Subtask load_to_mysql
[2024-04-15T00:11:58.464+0000] {task_command.py:426} INFO - Running <TaskInstance: extract_and_load_equipment_sensors.load_to_mysql scheduled__2023-06-20T00:00:00+00:00 [running]> on host cb5b33b73a08
[2024-04-15T00:11:58.639+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_and_load_equipment_sensors' AIRFLOW_CTX_TASK_ID='load_to_mysql' AIRFLOW_CTX_EXECUTION_DATE='2023-06-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-20T00:00:00+00:00'
[2024-04-15T00:11:58.641+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-15T00:11:58.647+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-15T00:11:58.648+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_equipment_sensors.py", line 29, in load_to_mysql
    return df.to_sql(table_name=, con=engine, if_exists='append', index=False)
                     ^^^^^^^^^^
NameError: name 'table_name' is not defined
[2024-04-15T00:11:58.668+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extract_and_load_equipment_sensors, task_id=load_to_mysql, execution_date=20230620T000000, start_date=20240415T001158, end_date=20240415T001158
[2024-04-15T00:11:58.691+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1461 for task load_to_mysql (name 'table_name' is not defined; 4942)
[2024-04-15T00:11:58.738+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-15T00:11:58.780+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-15T00:11:58.789+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
